CREATE TABLE [app].[Emails]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[From] NVARCHAR(255) NOT NULL,
	[To] NVARCHAR(255) NOT NULL,
	[Subject] NVARCHAR(255) NOT NULL,
	[Content] NVARCHAR(MAX) NOT NULL,
	[Date] DATETIME NOT NULL,
	CONSTRAINT [PK_app_Emails_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
)
