CREATE SCHEMA app AUTHORIZATION dbo
GO

CREATE SCHEMA administration AUTHORIZATION dbo
GO

CREATE SCHEMA meetings AUTHORIZATION dbo
GO

CREATE SCHEMA users AUTHORIZATION dbo
GO

CREATE SCHEMA registrations AUTHORIZATION dbo
GO

CREATE SCHEMA payments AUTHORIZATION dbo
GO